#spring.application.name=BookStore
spring:
  application:
    name: BookStore
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:29092
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret-key: 38fvze0661o1shjkkx8serxxhrkfgikhw2zdlsidsd48tm5amvqb0dbo6swivjrl


sendgrid:
  api-key: ${SENDGRID_API_KEY:}
  from-email: cuongdayne1811@gmail.com
